In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam

# Define the input data (flattened 2x2 grayscale image)
x_train = np.array([[0.2, 0.7, 0.3, 0.9]])

# Define the autoencoder architecture
input_dim = 4  # Size of input layer (2x2 image flattened)
encoding_dim = 2  # Size of encoded layer (latent space)

# Define the encoder model
input_layer = Input(shape=(input_dim,))
encoded = Dense(encoding_dim, activation='relu')(input_layer)

# Define the decoder model
decoded = Dense(input_dim, activation='sigmoid')(encoded)

# Create the autoencoder model
autoencoder = Model(inputs=input_layer, outputs=decoded)

# Compile the model
autoencoder.compile(optimizer=Adam(learning_rate=0.01), loss='mean_squared_error')

# Train the autoencoder
autoencoder.fit(x_train, x_train, epochs=500, verbose=0)

# Define the encoder model to extract encoded features
encoder = Model(inputs=input_layer, outputs=encoded)

# Encode the input data
encoded_data = encoder.predict(x_train)

# Decode the encoded data
decoded_data = autoencoder.predict(x_train)

# Extract weights and biases
encoder_weights = encoder.layers[1].get_weights()
decoder_weights = autoencoder.layers[2].get_weights()

print("Original Input Data:")
print(x_train)

print("Encoded Data:")
print(encoded_data)

print("Decoded Data (Reconstructed Input):")
print(decoded_data)

print("\nEncoder Weights:")
print("Weights:")
print(encoder_weights[0])
print("Biases:")
print(encoder_weights[1])

print("\nDecoder Weights:")
print("Weights:")
print(decoder_weights[0])
print("Biases:")
print(decoder_weights[1])


2024-08-02 11:02:09.610554: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-02 11:02:09.610729: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-02 11:02:09.772029: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Original Input Data:
[[0.2 0.7 0.3 0.9]]
Encoded Data:
[[0. 0.]]
Decoded Data (Reconstructed Input):
[[0.20117374 0.70000005 0.3000001  0.870458  ]]

Encoder Weights:
Weights:
[[-0.41066694 -1.2207297 ]
 [-0.5048952   0.64818496]
 [ 0.20936418  0.6282531 ]
 [ 0.317847   -0.3011134 ]]
Biases:
[ 0.         -0.25785753]

Decoder Weights:
Weights:
[[-0.36852217 -0.2202723  -0.91026187  0.44265175]
 [ 0.05470134  0.4470941  -1.0753297  -0.42937186]]
Biases:
[-1.3789746  0.847298  -0.8472974  1.9050145]


In [3]:
import numpy as np

# Define input data
x = np.array([0.2, 0.7, 0.3, 0.9])

# Define encoder weights and biases
W_e = encoder_weights[0]

b_e = encoder_weights[1]

# Define decoder weights and biases
W_d = decoder_weights[0]

b_d = decoder_weights[1]

# Define activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Encoding
def encode(x, W_e, b_e):
    linear_transformation = np.dot(x, W_e) + b_e
    return relu(linear_transformation)

# Decoding
def decode(encoded_x, W_d, b_d):
    linear_transformation = np.dot(encoded_x, W_d) + b_d
    return sigmoid(linear_transformation)

# Perform encoding
encoded_data = encode(x, W_e, b_e)
print("Encoded Data:")
print(encoded_data)

# Perform decoding
decoded_data = decode(encoded_data, W_d, b_d)
print("Decoded Data (Reconstructed Input):")
print(decoded_data)


Encoded Data:
[0. 0.]
Decoded Data (Reconstructed Input):
[0.20117374 0.70000003 0.3000001  0.87045802]


In [5]:
import numpy as np

# Define the original input data
x = np.array([0.2, 0.7, 0.3, 0.9])

# Define encoder weights and biases
W_e = np.array([
    [-0.4, -1.2],
    [-0.5, 0.6],
    [0.2, 0.6],
    [0.3, -0.3]
])

b_e = np.array([0.0, -0.2])

# Define decoder weights and biases
W_d = np.array([
    [-0.4, -0.2, -0.9, 0.4],
    [0.0, 0.4, -1.0, -0.4]
])

b_d = np.array([-1.3, 0.8, -0.8, 1.9])

# Define activation functions
def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Encoding function
def encode(x, W_e, b_e):
    linear_transformation = np.dot(x, W_e) + b_e
    return relu(linear_transformation)

# Decoding function
def decode(encoded_x, W_d, b_d):
    linear_transformation = np.dot(encoded_x, W_d) + b_d
    return sigmoid(linear_transformation)

# Perform encoding
encoded_data = encode(x, W_e, b_e)
print("Encoded Data:")
print(encoded_data)

# Perform decoding
decoded_data = decode(encoded_data, W_d, b_d)
print("Decoded Data (Reconstructed Input):")
print(decoded_data)


Encoded Data:
[0. 0.]
Decoded Data (Reconstructed Input):
[0.21416502 0.68997448 0.31002552 0.86989153]
